### ISSUE TITLE
Problem 1(a)

### ISSUE THREAD

**Issue by bob-skowron** [jasonwalker80/cse427s#25]
Are we supposed to sort somewhere? i'm getting a different answer than you 
[u'131.166.169.114/67858',
 u'254.253.248.193/3579',
 u'200.192.65.234/8897',
 u'62.193.77.201/169',
 u'237.64.198.45/4261',
 u'79.35.153.191/91',
 u'191.71.1.210/26287',
 u'181.208.88.8/59523',
 u'255.201.124.130/183',
 u'187.27.227.110/113']

**Comment by bob-skowron** [comment]
Also, do we think  ' ' is the best splitter? that technically breaks up the datetime as well.

**Comment by jasonwalker80** [comment]
(As mentioned via email), Inconsistencies in the order seems to be a common issue:
https://piazza.com/class/j6nxmwmqeet1zy?cid=307

I didn't use a sort, since the example output wasn't sorted by either IP, user ID or the composite key.

The ' ' split may not be the optimal solution. I'm sure a more complex regex could be used if that's expected. I'm open to ideas, but the ' ' split as-is seems to get the job done.

**Comment by bob-skowron** [comment]
closing because i think ' ' is fine for now and order doesnt matter
