### ISSUE TITLE
k-means implementation

### ISSUE THREAD

**Issue by bob-skowron** [jasonwalker80/cse427s#61]
@keon6kim have we verified that this actually runs out on a subset of data?

**Comment by keon6kim** [comment]
@bskowron23 
I tested it with small samples on pyspark script (instead of running script file with a command line) and it seemed to work.

But I have 2 concerns
1.  greatCircleDistance returns distance in miles but convergeDist = 0.1 isn't in the same unit of measurement (It's a Euclidean distance given lat,long pairs are x,y pairs). 
Neumann told me that it would probably be fine to use Euclidean distance, but I feel like  it's a topic worth discussing about.


2. I'm not sure if this would be a problem. But sometimes, as you are aware of, RDDs created from text files will be in a format as below:

u'value' 

instead of 

value.

I don't think this caused an error when I ran my test cases. But if it does, there should be a few more lines of code to clean up the formatting of the RDDs.

**Comment by bob-skowron** [comment]
interesting. I tried to run yours and it bombed out in multiple places. As to the concerns:
1. convergeDist is agnostic to the method. It is in whatever units we are working in. You can also return greatCircleDistance in km if you wanted to.
2. That shouldn't be a problem to adjust. Just convert them to floats.

**Comment by jasonwalker80** [comment]
Resolving.
